// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzkRqQLTs91iQwIOjzxKuGrcGT8NoaiyU',
    appId: '1:1002006310217:android:88e8c5df352e3647e0fe98',
    messagingSenderId: '1002006310217',
    projectId: 'forum-40aed',
    databaseURL: 'https://forum-40aed-default-rtdb.firebaseio.com',
    storageBucket: 'forum-40aed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpJFctJs8G1FNWJABrznAj52XQ4aZTFtg',
    appId: '1:1002006310217:ios:0dbbe4d5934636f9e0fe98',
    messagingSenderId: '1002006310217',
    projectId: 'forum-40aed',
    databaseURL: 'https://forum-40aed-default-rtdb.firebaseio.com',
    storageBucket: 'forum-40aed.appspot.com',
    iosClientId: '1002006310217-s8mn7ik49fep1h10kcre7n4r79ho0j30.apps.googleusercontent.com',
    iosBundleId: 'com.example.orca',
  );
}
